import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { clinicalInsightApi } from '../../core/api/clinicalInsightApi';
import { ClinicalNoteInsight, HumanReviewStatus, EntityCategory } from './types';

export const ClinicalInsightDetails: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [insight, setInsight] = useState<ClinicalNoteInsight | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [updating, setUpdating] = useState(false);

  const fetchInsight = async () => {
    if (!id) return;
    try {
      setLoading(true);
      const data = await clinicalInsightApi.getInsightById(id);
      setInsight(data);
    } catch (err) {
      setError('Failed to load clinical insight details.');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchInsight();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [id]);

  const handleReviewStatusUpdate = async (newStatus: HumanReviewStatus) => {
    if (!id || !insight) return;
    setUpdating(true);
    setError(null);
    try {
      await clinicalInsightApi.updateReviewStatus(id, {
        reviewStatus: newStatus,
        reviewedBy: 'CareCoordinatorUser' // Simulated
      });
      await fetchInsight();
    } catch (err: any) {
      setError(err.response?.data?.detail || 'Failed to update review status.');
    } finally {
      setUpdating(false);
    }
  };

  const getReviewStatusBadge = (status: HumanReviewStatus) => {
    switch (status) {
      case HumanReviewStatus.PendingReview: return <span className="badge" style={{ background: '#fefcbf', color: '#744210' }}>Pending Review</span>;
      case HumanReviewStatus.Reviewed: return <span className="badge" style={{ background: '#e2e8f0', color: '#4a5568' }}>Reviewed</span>;
      case HumanReviewStatus.Approved: return <span className="badge" style={{ background: '#c6f6d5', color: '#22543d' }}>Approved</span>;
      case HumanReviewStatus.Rejected: return <span className="badge" style={{ background: '#fed7d7', color: '#822727' }}>Rejected</span>;
      case HumanReviewStatus.RequiresClarification: return <span className="badge" style={{ background: '#feebc8', color: '#9c4221' }}>Requires Clarification</span>;
      default: return <span className="badge">Unknown</span>;
    }
  };

  if (loading) return <div className="page-section"><p>Loading insight...</p></div>;
  if (!insight) return <div className="page-section"><p style={{ color: 'red' }}>Insight not found.</p></div>;

  return (
    <div className="page-section">
      <div className="section-header" style={{ marginBottom: '20px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <Link to="/clinical-insights" style={{ textDecoration: 'none', color: '#62707d', fontWeight: 600 }}>&larr; Back</Link>
          <h2 style={{ margin: 0 }}>Clinical Insight Details</h2>
          {getReviewStatusBadge(insight.humanReviewStatus)}
        </div>
      </div>

      <div style={{ padding: '12px', background: '#e2e8f0', color: '#2d3748', borderRadius: '4px', marginBottom: '20px', fontSize: '0.9rem' }}>
        <strong>Responsible AI Notice:</strong> This is assistive demo output generated by <code>{insight.aiProviderName}</code>. It requires human review and is not a medical diagnosis.
      </div>

      {error && <div style={{ color: 'red', marginBottom: '16px', padding: '12px', background: '#ffe6e6', borderRadius: '4px' }}>{error}</div>}

      <div className="module-grid" style={{ gridTemplateColumns: '2fr 1fr' }}>
        
        {/* Left Column: Note and Outputs */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          
          <div className="info-panel">
            <h3>Original Note (Synthetic)</h3>
            <div style={{ background: '#f8fafc', padding: '16px', borderRadius: '4px', border: '1px solid #e2e8f0', whiteSpace: 'pre-wrap', marginTop: '12px' }}>
              {insight.clinicalNoteText}
            </div>
          </div>

          <div className="info-panel">
            <h3>Extracted Entities</h3>
            {insight.extractedEntities && insight.extractedEntities.length > 0 ? (
              <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '12px', textAlign: 'left' }}>
                <thead>
                  <tr style={{ borderBottom: '2px solid #d9e4e7' }}>
                    <th style={{ padding: '8px' }}>Text</th>
                    <th style={{ padding: '8px' }}>Category</th>
                    <th style={{ padding: '8px' }}>Confidence</th>
                  </tr>
                </thead>
                <tbody>
                  {insight.extractedEntities.map(e => (
                    <tr key={e.entityId} style={{ borderBottom: '1px solid #d9e4e7' }}>
                      <td style={{ padding: '8px', fontWeight: 600 }}>{e.text}</td>
                      <td style={{ padding: '8px' }}>{EntityCategory[e.category]}</td>
                      <td style={{ padding: '8px' }}>{(e.confidenceScore * 100).toFixed(0)}%</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            ) : (
              <p style={{ marginTop: '12px', color: '#62707d' }}>No entities extracted.</p>
            )}
          </div>

        </div>

        {/* Right Column: Risk Indicators and Review Action */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px', alignSelf: 'start' }}>
          
          <div className="info-panel">
            <h3>Workflow & Metadata</h3>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', marginTop: '16px' }}>
              <div>
                <strong>Patient ID</strong>
                <span style={{ display: 'block' }}>{insight.patientId}</span>
              </div>
              <div>
                <strong>Provider ID</strong>
                <span style={{ display: 'block' }}>{insight.providerId}</span>
              </div>
              <div>
                <strong>Created At</strong>
                <span style={{ display: 'block' }}>{new Date(insight.createdAt).toLocaleString()}</span>
              </div>
              {insight.reviewedBy && (
                <div>
                  <strong>Reviewed By</strong>
                  <span style={{ display: 'block' }}>{insight.reviewedBy} at {insight.reviewedTimestamp ? new Date(insight.reviewedTimestamp).toLocaleString() : ''}</span>
                </div>
              )}
            </div>
          </div>

          <div className="info-panel">
            <h3>Risk Indicators</h3>
            {insight.riskIndicators && insight.riskIndicators.length > 0 ? (
              <ul style={{ paddingLeft: '20px', marginTop: '12px' }}>
                {insight.riskIndicators.map((r, i) => <li key={i} style={{ color: '#822727', fontWeight: 600 }}>{r}</li>)}
              </ul>
            ) : (
              <p style={{ color: '#62707d', marginTop: '12px' }}>None detected.</p>
            )}

            <h3 style={{ marginTop: '20px' }}>Suggested Follow-Ups</h3>
            {insight.suggestedFollowUpTopics && insight.suggestedFollowUpTopics.length > 0 ? (
              <ul style={{ paddingLeft: '20px', marginTop: '12px' }}>
                {insight.suggestedFollowUpTopics.map((s, i) => <li key={i}>{s}</li>)}
              </ul>
            ) : (
              <p style={{ color: '#62707d', marginTop: '12px' }}>None detected.</p>
            )}
          </div>

          <div className="info-panel" style={{ background: '#fdfaed', border: '1px solid #feebc8' }}>
            <h3>Human Review Action</h3>
            <p style={{ fontSize: '0.9rem', color: '#744210', marginBottom: '16px' }}>All AI output must be reviewed before actionable use in care coordination.</p>
            
            <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
              {insight.humanReviewStatus === HumanReviewStatus.PendingReview && (
                <>
                  <button disabled={updating} onClick={() => handleReviewStatusUpdate(HumanReviewStatus.Approved)} style={{ padding: '8px', background: '#c6f6d5', color: '#22543d', border: '1px solid #22543d', borderRadius: '4px', cursor: 'pointer', fontWeight: 600 }}>Approve Insight</button>
                  <button disabled={updating} onClick={() => handleReviewStatusUpdate(HumanReviewStatus.Rejected)} style={{ padding: '8px', background: '#fed7d7', color: '#822727', border: '1px solid #822727', borderRadius: '4px', cursor: 'pointer', fontWeight: 600 }}>Reject Insight</button>
                  <button disabled={updating} onClick={() => handleReviewStatusUpdate(HumanReviewStatus.RequiresClarification)} style={{ padding: '8px', background: '#feebc8', color: '#9c4221', border: '1px solid #9c4221', borderRadius: '4px', cursor: 'pointer', fontWeight: 600 }}>Requires Clarification</button>
                </>
              )}

              {insight.humanReviewStatus !== HumanReviewStatus.PendingReview && (
                <p style={{ fontStyle: 'italic', color: '#744210' }}>Review already processed.</p>
              )}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};
